export const SET_FIRST_NAME = "SET_FIRST_NAME";

export const SET_LAST_NAME = "SET_LAST_NAME";

export const SET_HIGHLIGHTED_FIRST_NAME = "SET_HIGHLIGHTED_FIRST_NAME";

export const SET_HIGHLIGHTED_LAST_NAME = "SET_HIGHLIGHTED_LAST_NAME";
